server: 
  port: 2333
  address: 0.0.0.0
spring: 
  main:
    banner-mode: log
lavalink:
  server:
    password: "teste"
    sources:
      youtube: true
      soundcloud: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    youtubeSearchEnable: true
    soundcloudSearchEnable: true
    gc-warnings: true

metrics:
  prometheus:
    enable: false
    endpoint: /metrics

sentry:
  dns: ""

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO